/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yuhui_jnitest_jni_JniUtil */

#ifndef _Included_com_example_yuhui_jnitest_jni_JniUtil
#define _Included_com_example_yuhui_jnitest_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yuhui_jnitest_jni_JniUtil
 * Method:    append
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yuhui_jnitest_jni_JniUtil_append
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
